<?php
/* Load category by id*/
$cat = Mage::getModel('catalog/category')->load(9);
/*Returns comma separated ids*/
$subcats = $cat->getChildren();
$skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'/frontend/rwd/parts/images/';
$_helper = $this->helper('catalog/output');
$products = Mage::getModel("catalog/product")
    ->getCollection()
    ->addAttributeToSelect('*')
    ->setOrder('entity_id', 'DESC')
    ->setPageSize(3)->load();

$prod = Mage ::getModel("catalog/product")
->getCollection()
    ->addAttributeToSelect('*')
    ->setOrder('entity_id')
    ->setPageSize(6)->load();

?>



<div class="container-fluid" style="background-color: #ffffff;">
    <div class="container mobile-parts">
        <h2 class="text-header" style="margin-bottom: 30px !important">Frequently searched parts</h2>
        <?php foreach($prod as $pr):?>
            <!--<div class="col-md-3 media1"> <span class="media-left"> <img src="<?php /*echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(true)->resize(300); */?>"  alt="" style="width:100px !important;height:100px !important"> </span>
                <div class="media-body" style="border-right: 1px solid #000000">
                    <p style="font-size: 13px" class="media-heading1"><?php /*echo $_helper->productAttribute($product, $product->getName() , 'name'); */?> </p>
                    <p class="media-heading" style="color: #fd8b25">₹ <?php /*echo $_helper->productAttribute($product, $product->getPrice() , 'price'); */?></p>
                    <div class="vdivider"></div>
                </div>
            </div>-->
            <div class="col-md-2 col-sm-2 cell"> <a href="<?php echo $pr->getProductUrl()?>"><img src="<?php echo  $this->helper('catalog/image')->init($pr, 'small_image')->keepFrame(true)->resize(300);?>" class="img-responsive"></a>
                <p><?php echo $_helper->productAttribute($pr, $pr->getName() , 'name');?></p>
            </div>
        <?php endforeach;?>
    <!--<div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra1.png"*/?>" class="img-responsive"></a>
        <p>Lubricants</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra2.png"*/?>" class="img-responsive"></a>
        <p>Engine</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra3.png"*/?>" class="img-responsive"></a>
        <p>Electric components</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra1.png"*/?>" class="img-responsive"></a>
        <p>Lubricants</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra3.png"*/?>" class="img-responsive"></a>
        <p>Electric components</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra2.png"*/?>" class="img-responsive"></a>
        <p>Engine</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra5.png"*/?>" class="img-responsive"></a>
        <p>Exhaust system</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra6.png"*/?>" class="img-responsive"></a>
        <p>Suspension</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra1.png"*/?>" class="img-responsive"></a>
        <p>Lubricants</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra4.png"*/?>" class="img-responsive"></a>
        <p>Universal</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra5.png"*/?>" class="img-responsive"></a>
        <p>Exhaust system</p>
    </div>
    <div class="col-md-2 col-sm-2 cell"> <a href="product-listing.html"><img src="<?php /*echo $skinUrl."ra1.png"*/?>" class="img-responsive"></a>
        <p>Lubricants</p>
    </div>-->
  <!-- <?php /*foreach(explode(',',$subcats) as $subCatid):*/?>

    <?php /*$_category = Mage::getModel('catalog/category')->load($subCatid);*/?>

       <div class="col-md-2 col-sm-2 cell"> <a href="<?php /*echo $_category->getURL()*/?>"><img src="<?php /*echo $_category->getImageUrl()*/?>" class="img-responsive"></a>
           <p><?php /*echo $_category->getName()*/?></p>
       </div>

    --><?php /*endforeach;*/?>

</div>
</div>
<br>

<div class="container-fluid" style="background-color: #ffffff;">
<div class="container-custom offers-section">
    <h2 class="text-header2" style="margin-bottom: 30px !important">Offers that save you a lot of money</h2>
    <div class="offers text-header"> <span> <img src="<?php echo $skinUrl."offer1.png"?>"> <img src="<?php echo $skinUrl."offer2.png"?>"> <img src="<?php echo $skinUrl."offer3.png"?>"> <img src="<?php echo $skinUrl."offer4.png"?>"> </span> </div>
</div>
    </div>





<div class="container">
    <h2>Recently added parts</h2>
</div>
<div class="container-fluid parts-section" style="margin-top: 30px;background-color: #efefef;height: 150px">
    <?php foreach($products as $product):?>
    <div class="col-md-3 media1"> <span class="media-left"> <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(true)->resize(300); ?>"  alt="" style="width:100px !important;height:100px !important"> </span>
        <div class="media-body" style="border-right: 1px solid #000000">
            <p style="font-size: 13px" class="media-heading1"><?php echo $_helper->productAttribute($product, $product->getName() , 'name'); ?> </p>
            <p class="media-heading" style="color: #fd8b25">₹ <?php echo $_helper->productAttribute($product, $product->getPrice() , 'price'); ?></p>
            <div class="vdivider"></div>
        </div>
    </div>
    <?php endforeach;?>
    <div class="col-md-3 media1">
        <h5>SEE ALL RECENTLY ADDED PARTS</h5>
        <button class="button button5" onclick= setLocation("<?php echo Mage::getUrl('products.html')?>") >SHOP NOW</button>


    </div>
</div>

<script>
    jQuery(document).ready(function(e){
        jQuery('.search-panel .dropdown-menu').find('a').click(function(e) {
            e.preventDefault();
            var param = jQuery(this).attr("href").replace("#","");
            var concept = jQuery(this).text();
            jQuery('.search-panel span#search_concept').text(concept);
            jQuery('.input-group #search_param').val(param);
        });
    });
</script>
<script type="text/javascript">
    jQuery(function(){

        jQuery('#slider1').Thumbelina({
            $bwdBut:jQuery('#slider1 .left'),    // Selector to left button.
            $fwdBut:jQuery('#slider1 .right')    // Selector to right button.
        });

        jQuery('#slider2').Thumbelina({
            $bwdBut:jQuery('#slider2 .left'),    // Selector to left button.
            $fwdBut:jQuery('#slider2 .right')    // Selector to right button.
        });

        jQuery('#slider3').Thumbelina({
            orientation:'vertical',         // Use vertical mode (default horizontal).
            $bwdBut:jQuery('#slider3 .top'),     // Selector to top button.
            $fwdBut:jQuery('#slider3 .bottom')   // Selector to bottom button.
        });

    })
</script>
<style type="text/css">
    #slider2 {
        position: relative;
        margin-left: 20px;
        width: 85%;
        height: 120px;
    }
</style>
<script type="application/javascript">
    function show(){
        document.getElementById("test").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test2").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test3").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test4").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
    }
    function hide(){
        document.getElementById("test").innerHTML= "";
        document.getElementById("test2").innerHTML= "";
        document.getElementById("test3").innerHTML= "";
        document.getElementById("test4").innerHTML= "";
    }
</script>
<script>
    /*(function(){
     var imgLen = document.getElementById('slider2');
     var images = imgLen.getElementsByTagName('img');
     var counter = 1;

     if(counter <= images.length){
     setInterval(function(){
     images[0].src = images[counter].src;
     console.log(images[counter].src);
     counter++;

     if(counter === images.length){
     counter = 1;
     }
     },4000);
     }
     })();*/
</script>
<script>
    /*jQuery(function() {
     jQuery("li:first-child").addClass("hover-effect");
     jQuery(".hover-effect").mouseover(function() {
     jQuery(this).removeClass("hover-effect");
     });
     });*/
    jQuery(document).ready(function()
    {
        jQuery("#image-data li:first-child").addClass("hover-effect");
        jQuery(".hover-effect").mouseout(function() {
            jQuery(this).removeClass("hover-effect");
        });
    })
</script>
</html>
