
<?php
$tempArray = array();
$productIdArray  = array();
if (Mage::getSingleton('customer/session')->isLoggedIn()) {

    $orders= Mage::getModel('sales/order')->getCollection()->addAttributeToFilter('customer_id',Mage::getSingleton('customer/session')->getCustomer()->getId());
    foreach($orders as $eachOrder){
        $order = Mage::getModel("sales/order")->load($eachOrder->getId());

        $items = $order->getAllVisibleItems();
        foreach($items as $item):
            $productIdArray[] = $item->getProductId();
        endforeach;
    }
}
$customerPastOrderItems = array_unique($productIdArray);

?>



<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $_productCollection  = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
        ->addAttributeToSelect('*')
        /*->setOrder('entity_id')*/
        ->setPageSize(4)->load();
}
/*$storeId = Mage::app()->getStore()->getId();

$_productCollection = Mage::getResourceModel('reports/product_collection')
    ->addAttributeToSelect('*')
    ->setStoreId($storeId)
    ->addStoreFilter($storeId)
    ->addViewsCount()
    ->setPageSize(4)->load();*/
?>

<?php
/* Load category by id*/
$cat = Mage::getModel('catalog/category')->load(9);
/*Returns comma separated ids*/
$subcats = $cat->getChildren();
$skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'/frontend/rwd/parts/images/';
$_helper = $this->helper('catalog/output');
$products = Mage::getModel("catalog/product")
    ->getCollection()
    ->addAttributeToSelect('*')
    ->setOrder('entity_id', 'DESC')
    ->setPageSize(3)->load();

$prod = Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()
    ->addAttributeToSelect('*')
    ->setOrder('entity_id')
    ->setPageSize(6)->load();

?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) :?>
<div class="container-fluid">
    <div class="container"> <br>
        <h2>Parts You Recently Searched</h2>
        <div class="carousel slide" id="myCarousel2">
            <nav>
                <ul class="control-box pager">
                    <li><a data-slide="prev" href="#myCarousel2" class=""><i class="glyphicon glyphicon-chevron-left"></i></a></li>
                    <li><a data-slide="next" href="#myCarousel2" class=""><i class="glyphicon glyphicon-chevron-right"></i></a></li>
                </ul>
            </nav>
            <!-- /.control-box -->
            <div class="carousel-inner" style="margin-left: -20px">
                <?php /*for($i=1; $i<=2;$i++): */?>
               <!-- --><?php /*if($i == 1):*/?>
                <!--<div class="item active">-->
                    <ul class="thumbnails">
                        <?php foreach($_productCollection as $prodData):?>
                        <li class="col-sm-3" style="">
                            <div class="card" style="background-color: #efefef">
                                <div class="card-custom"> <a href="<?php echo $prodData->getProductUrl()?>"><img class="cardimage" src="<?php echo  $this->helper('catalog/image')->init($prodData, 'small_image')->keepFrame(true)->resize(300);?>"" alt=""></a>
                                    <div class="card-block">
                                        <a href="<?php echo $prodData->getProductUrl()?>"><h4 style="text-transform: uppercase" class="card-title text-center"><?php echo $prodData->getName()?></h4></a>
                                        <p class="card-text text-center" style="color: #A9A9A9">OPTIMAL</p>
                                        <div class="text-center"> <a class="btn btn-success" href="<?php echo Mage::helper('checkout/cart')->getAddUrl($prodData)?>" style="margin-bottom: 10px !important"> <i class="fa fa-shopping-cart fa-lg"></i> ADD TO CART</a> </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php endforeach;?>
                    </ul>
               <!-- </div>-->
                <?php /*else:*/?><!--
                <div class="item left next">
                    <ul class="thumbnails">
                        <?php /*foreach($_productCollection as $prodData):*/?>
                            <li class="col-sm-3" style="">
                                <div class="card" style="background-color: #efefef">
                                    <div class="card-custom"> <a href="<?php /*echo $prodData->getProductUrl()*/?>"><img class="cardimage" src="<?php /*echo  $this->helper('catalog/image')->init($prodData, 'small_image')->keepFrame(true)->resize(300);*/?>"" alt=""></a>
                                        <div class="card-block">
                                            <a href="<?php /*echo $prodData->getProductUrl()*/?>"><h4 style="text-transform: uppercase" class="card-title text-center"><?php /*echo $prodData->getName()*/?></h4></a>
                                            <p class="card-text text-center" style="color: #A9A9A9">OPTIMAL</p>
                                            <div class="text-center"> <a class="btn btn-success" href="<?php /*echo Mage::helper('checkout/cart')->getAddUrl($prodData)*/?>" style="margin-bottom: 10px !important"> <i class="fa fa-shopping-cart fa-lg"></i> ADD TO CART</a> </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php /*endforeach;*/?>
                    </ul>
                </div>-->
               <!-- --><?php /*endif;*/?>
               <!-- --><?php /*endfor; */?>
                <!-- /Slide2 -->
            </div>
        </div>
        <!-- /#myCarousel -->
    </div>
    <!-- /.container -->
</div>
<div class="container-fluid" style="background-color: #efefef">
    <div class="container"> <br>
        <h2>Parts you bought in the past</h2>
        <div class="carousel slide" id="myCarousel1">
            <nav>
                <ul class="control-box pager">
                    <li><a data-slide="prev" href="#myCarousel1" class=""><i class="glyphicon glyphicon-chevron-left"></i></a></li>
                    <li><a data-slide="next" href="#myCarousel1" class=""><i class="glyphicon glyphicon-chevron-right"></i></a></li>
                </ul>
            </nav>
            <!-- /.control-box -->
            <div class="carousel-inner" style="margin-left: -20px">
                <div class="item active">
                    <ul class="thumbnails">
                        <?php $i=0 ?>
                        <?php foreach($customerPastOrderItems as $id):?>
                            <?php if($i<=3):?>
                            <?php $prodDataA = Mage::getModel('catalog/product')->load($id) ?>

                        <li class="col-sm-3">
                            <div class="card" style="background-color: #ffffff">
                                <div class="card-custom"> <a href="<?php echo $prodDataA->getProductUrl()?>"><img class="cardimage" src="<?php echo  $this->helper('catalog/image')->init($prodDataA, 'small_image')->keepFrame(true)->resize(300);?>" alt=""></a>
                                    <div class="card-block">
                                        <a href="<?php echo $prodDataA->getProductUrl()?>"><h4 style="text-transform: uppercase" class="card-title text-center"><?php echo $prodDataA->getName()?></h4></a>
                                        <p class="card-text text-center" style="color: #A9A9A9">OPTIMAL</p>
                                        <div class="text-center"> <a class="btn btn-success" href="<?php echo Mage::helper('checkout/cart')->getAddUrl($prodDataA)?>" style="margin-bottom: 10px !important"> <i class="fa fa-shopping-cart fa-lg"></i> ADD TO CART</a> </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                            <?php $i++ ?>
                            <?php endif; ?>
                        <?php endforeach;?>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /#myCarousel -->
    </div>
    <!-- /.container -->
</div>

<?php endif;?>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()):?>
<div style="display:none; class="container-fluid" style="background-color: #ffffff;">
    <div class="container mobile-parts">
        <h2 class="text-header" style="margin-bottom: 30px !important">Frequently searched parts</h2>
        <?php foreach($prod as $pr):?>
            <div class="col-md-2 col-sm-2 cell"> <a href="<?php echo $pr->getProductUrl()?>"><img src="<?php echo  $this->helper('catalog/image')->init($pr, 'small_image')->keepFrame(true)->resize(300);?>" class="img-responsive"></a>
                <p><?php echo $_helper->productAttribute($pr, $pr->getName() , 'name');?></p>
            </div>
        <?php endforeach;?>

</div>
</div>
<?php else: ?>
    <div class="container-fluid" style="background-color: #ffffff;">
    <div class="container mobile-parts">
        <h2 class="text-header" style="margin-bottom: 30px !important">Frequently searched parts</h2>
        <?php foreach($prod as $pr):?>
            <div class="col-md-2 col-sm-2 cell"> <a href="<?php echo $pr->getProductUrl()?>"><img src="<?php echo  $this->helper('catalog/image')->init($pr, 'small_image')->keepFrame(true)->resize(300);?>" class="img-responsive"></a>
                <p><?php echo $_helper->productAttribute($pr, $pr->getName() , 'name');?></p>
            </div>
        <?php endforeach;?>

    </div>
    </div>
<?php  endif;?>
<br>

<div class="container-fluid" style="background-color: #ffffff;">
<div class="container offers-section">
    <h2 class="text-header2" style="margin-bottom: 30px !important">Offers that save you a lot of money</h2>
    <div class="offers"> <span> <img src="<?php echo $skinUrl."offer1.png"?>"> <img src="<?php echo $skinUrl."offer2.png"?>"> <img src="<?php echo $skinUrl."offer3.png"?>"> <img src="<?php echo $skinUrl."offer4.png"?>"> </span> </div>
</div>
    </div>
<br>





<div class="container">
    <h2>Recently added parts</h2>
</div>
<div class="container-fluid parts-section" style="margin-top: 30px;background-color: #efefef;height: 150px">
    <?php foreach($products as $product):?>
    <div class="col-md-3 media1"> <span class="media-left"> <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->keepFrame(true)->resize(300); ?>"  alt="" style="width:100px !important;height:100px !important"> </span>
        <div class="media-body" style="border-right: 1px solid #000000">
            <p style="font-size: 13px" class="media-heading1"><?php echo $_helper->productAttribute($product, $product->getName() , 'name'); ?> </p>
            <p class="media-heading" style="color: #fd8b25">₹ <?php echo $_helper->productAttribute($product, $product->getPrice() , 'price'); ?></p>
            <div class="vdivider"></div>
        </div>
    </div>
    <?php endforeach;?>
    <div class="col-md-3 media1">
        <h5>SEE ALL RECENTLY ADDED PARTS</h5>
        <button class="button button5" onclick= setLocation("<?php echo Mage::getUrl('products.html')?>") >SHOP NOW</button>


    </div>
</div>

<script>
    jQuery(document).ready(function(e){
        jQuery('.search-panel .dropdown-menu').find('a').click(function(e) {
            e.preventDefault();
            var param = jQuery(this).attr("href").replace("#","");
            var concept = jQuery(this).text();
            jQuery('.search-panel span#search_concept').text(concept);
            jQuery('.input-group #search_param').val(param);
        });
    });
</script>
<script type="text/javascript">
    jQuery(function(){

        jQuery('#slider1').Thumbelina({
            $bwdBut:jQuery('#slider1 .left'),    // Selector to left button.
            $fwdBut:jQuery('#slider1 .right')    // Selector to right button.
        });

        jQuery('#slider2').Thumbelina({
            $bwdBut:jQuery('#slider2 .left'),    // Selector to left button.
            $fwdBut:jQuery('#slider2 .right')    // Selector to right button.
        });

        jQuery('#slider3').Thumbelina({
            orientation:'vertical',         // Use vertical mode (default horizontal).
            $bwdBut:jQuery('#slider3 .top'),     // Selector to top button.
            $fwdBut:jQuery('#slider3 .bottom')   // Selector to bottom button.
        });

    })
</script>
<style type="text/css">
    #slider2 {
        position: relative;
        margin-left: 20px;
        width: 85%;
        height: 120px;
    }
</style>
<script type="application/javascript">
    function show(){
        document.getElementById("test").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test2").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test3").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
        document.getElementById("test4").innerHTML= "<li>DIO</li><li>ACTIVA</li><li>CBR 150</li><li>CBR 250</li>";
    }
    function hide(){
        document.getElementById("test").innerHTML= "";
        document.getElementById("test2").innerHTML= "";
        document.getElementById("test3").innerHTML= "";
        document.getElementById("test4").innerHTML= "";
    }
</script>
<script>
    /*(function(){
     var imgLen = document.getElementById('slider2');
     var images = imgLen.getElementsByTagName('img');
     var counter = 1;

     if(counter <= images.length){
     setInterval(function(){
     images[0].src = images[counter].src;
     console.log(images[counter].src);
     counter++;

     if(counter === images.length){
     counter = 1;
     }
     },4000);
     }
     })();*/
</script>
<script>
    /*jQuery(function() {
     jQuery("li:first-child").addClass("hover-effect");
     jQuery(".hover-effect").mouseover(function() {
     jQuery(this).removeClass("hover-effect");
     });
     });*/
    jQuery(document).ready(function()
    {
        jQuery("#image-data li:first-child").addClass("hover-effect");
        jQuery(".hover-effect").mouseout(function() {
            jQuery(this).removeClass("hover-effect");
        });
    })
</script>
</html>
